# general
seed: 42
workers: 0
dataset_dir: "./datasets"

# train options
batch_size: 80 # original set to 256
image_size: 224 # original set to 224
start_epoch: 0
epochs: 100
dataset: "CIFAR-10" # CIFAR-10 / CIFAR-100 / STL-10 / ImageNet-10 / ImageNet-dogs / tiny-ImageNet

# model options
resnet: "ResNet18" # ResNet18 / ResNet34 / ResNet50
feature_dim: 128
model_path: "save/CIFAR-10-100-64-224Epoch"
reload: False

# loss options
learning_rate: 0.0003 # original set to 3e-4
weight_decay: 0.
instance_temperature: 0.5
cluster_temperature: 1.0
